blank_issues_enabled: false
contact_links:
    - name: â“ Ask Question
      url: https://github.com/Automattic/gravatar/discussions
      about: Ask questions and discuss with other community members
